### ISSUE TITLE
TimelaneCore cannot be compiled with a Mac target

### ISSUE THREAD

**Issue by shpakovski** [icanzilb/TimelaneCore#1]
Hi Marin, thanks a lot for building this promising tool!

Could you please change the version number to macOS 10.15 here? https://github.com/icanzilb/TimelaneCore/blob/884d9caaba3c8fc30101cb4e0ad18e47f1603e8e/Package.swift#L9

Thanks in advance 🙏

**Comment by icanzilb** [comment]
Is there an API not available on 10.14?

**Comment by shpakovski** [comment]
@icanzilb Ouch, I didn’t mention, sorry. Yes, the `OSLog.Category.dynamicStackTracing` is marked as 10.10+ in Apple’s documentation but it’s available only on modern macOS.

**Comment by icanzilb** [comment]
Oh yeah - I see, I'll add a fallback for older macOS versions, thanks!

**Comment by icanzilb** [comment]
Taken care of on `master` https://github.com/icanzilb/TimelaneCore/commit/e009f7d40e8313af3dd536eec99436546f364377 - will cut a new version next week 

Thank you very much for catching this
