### ISSUE TITLE
Cutoff value

### ISSUE THREAD

**Issue by danielbyon** [icanzilb/TimelaneCore#18]
Why is the cutoff for values 50 characters? Is it an os_log constraint?

**Comment by danielbyon** [comment]
Any update on this? According to the headers, I'm seeing a platform limitation of 1024 characters for os_log, is that the same for os_signpost?

**Comment by icanzilb** [comment]
Hey no, no updates the limit is arbitrary - something that can be reasonably display in the Instruments UI. How would a popover over the timeline look like with something over a 1000 characters long?

**Comment by danielbyon** [comment]
Looks like it doesn't have a hover popup when hovering over an event in the Events Over Time instrument. Is there any way to pass data to the detail panel on the right side of the window?

I integrated this by hooking Timelane up into our existing logging functions, but some of our logging statements have long prefixes (like the type/name of an Operation), and that eats up most if not all of the 50 character limit. I probably wouldn't want to allow 1000+ characters, but something like 100 or so would make the events more usable for us, and we can always expand the window to see the text in the table view.

Can we get a hook to set/override the 50 character limit?

**Comment by icanzilb** [comment]
Here's a sample video of how the value events display on the timeline in the Events over time instrument: https://vimeo.com/395904461 Sadly, there is no way to display a more detailed information in the sidebar on the right (or at least I cannot find a way to do that)

I do understand the issue though, I think 50 is a reasonable default to keep the Instruments UI clean and usable, but it's worth into adding a way to log larger data. I'll think about how can it be done nicely so the Combine, RxSwift, etc. bindings can also make use of this.

**Comment by icanzilb** [comment]
Fixed in https://github.com/icanzilb/TimelaneCore/pull/29
