### ISSUE TITLE
Use OptionSet for filter parameter

### ISSUE THREAD

**Issue by nkristek** [icanzilb/TimelaneCore#21]
I propose to change the type of the `filter` parameter use an `OptionSet` instead of `Set` since it provides more functionality than `Set`.

`OptionSet` implementation:
```swift
public struct LaneTypeOptions: OptionSet {
    public let rawValue: Int
    public init(rawValue: Int) {
        self.rawValue = rawValue
    }
    public static let subscription: LaneTypeOptions = .init(rawValue: 1 << 0)
    public static let event: LaneTypeOptions        = .init(rawValue: 1 << 1)
    public static let all: LaneTypeOptions          = [.subscription, .event]
}
```
Function signature will be:
```swift
func lane(/* ... */
          filter: Timelane.LaneTypeOptions = .all,
          /* ... */)

```

**Comment by icanzilb** [comment]
Oh yeah, that seems very reasonable 👍🏼 `OptionSet` seems like the right type to use here. Does any of the call sites needs to change in any way?

**Comment by nkristek** [comment]
This addition makes it possible to change existing extension methods to require the OptionSet parameter (source-breaking) or add new extensions in addition to the existing ones.
I guess, only call sites which are explicitly providing a Set (declaring it with let before calling the function) would need to be adjusted, if they call the function like the following, it should be fine:

```swift
// still possible:
signal.handle("stream", filter: [.subscription, .event])

// now also possible:
signal.handle("stream", filter: .all)
signal.handle("stream", filter: .subscription)
signal.handle("stream", filter: .event)

// source-breaking:
signal.handle("stream", filter: Set([.event]))
```

BTW, great talk yesterday on UIKonf, I noticed this tool through it and since then have written an extension to use it with ReactiveSwift. It's great to use and I will soon use it to debug a memory leak which has been bugging me for a while now but is very hard to locate.
What would be the preferred way of publishing the ReactiveSwift extension? Should I create a new repository like you did for RxSwift?

**Comment by icanzilb** [comment]
Thank you, it has to be in its own repo to work with SwiftPM atm. If you push it to GitHub I can link from Timelane's website and the other repos 👍🏼
