### ISSUE TITLE
ReactiveSwift extension

### ISSUE THREAD

**Issue by nkristek** [icanzilb/TimelaneCore#23]
As previously mentioned, I've created an extension for [ReactiveSwift](https://github.com/ReactiveCocoa/ReactiveSwift) called [ReactiveTimelane](https://github.com/nkristek/ReactiveTimelane).
I still need to write proper unit tests for it, but from my local testing it seems to work fine.
I hope it's alright that for the readme I used the structure of `RxTimelane` and modified it a bit (btw I noticed it says `TimelaneCombine` at the SwiftPM part).
Let me know what you think!

**Comment by icanzilb** [comment]
Super cool @nkristek ! I'll have a look at the code but meanwhile I shared here https://twitter.com/icanzilb/status/1265246950745673730 and a couple of slacks - maybe someone who has existing ReactiveSwift code can help test 👍🏼

**Comment by icanzilb** [comment]
@nkristek I just pushed an update to both RxTimelane/TimelaneCombine to move creating a subscription from the lane() operator to the closure used when a new subscription is made to the observable/publisher: https://github.com/icanzilb/RxTimelane/blob/master/Sources/RxTimelane/RxTimelane.swift#L37

This fixes an issue when two subscriptions are made on a non-shared publisher as reported here:
https://github.com/icanzilb/RxTimelane/issues/14

I'm not sure if that's relevant for ReactiveSwift but if you have a look at the linked issue you can figure out if you also need to move the code that creates the subscription

**Comment by nkristek** [comment]
I'll look into it!

**Comment by nkristek** [comment]
I've checked and it doesn't seem to be an issue for ReactiveSwift.
