### ISSUE TITLE
Double colons are not permitted when transforming a value

### ISSUE THREAD

**Issue by nkristek** [icanzilb/TimelaneCore#24]
While writing unit tests for `ReactiveTimelane` I have encountered that double colons `:` are not permitted in the `transformValue` closure. When using a double colon inside the closure, the resulting `String` is not appended to the value that is logged.

Example in a unit test:
```swift
SignalProducer(value: 1)
    .lane("Test Subscription",
              filter: .event,
              transformValue: { "TEST: \($0)" },
              logger: recorder.log)
    .start()
XCTAssertEqual(recorder.logged.count, 2)
XCTAssertEqual(recorder.logged[0].outputTldr, "Output, Test Subscription, TEST: 1")
```
The resulting error is 
`XCTAssertEqual failed: ("Output, Test Subscription, ") is not equal to ("Output, Test Subscription, TEST 1")`

**Comment by icanzilb** [comment]
Interesting finding - the value delimiter in the protocol is `###` so this should be working. 

This might be actually an issue on Instruments' side when it's parsing the messages.

https://github.com/icanzilb/Timelane/blob/master/Instrument/TimelaneInstrument.instrpkg#L136

I'll get a reproducible test case and find the core issue

**Comment by icanzilb** [comment]
@nkristek did you find out what was the problem with colons? I tried to reproduce but it seems like colons are printed just fine in Instruments?

<img width="625" alt="image" src="https://user-images.githubusercontent.com/633862/85947895-b3e57080-b94d-11ea-8c6f-e572435582a7.png">

**Comment by nkristek** [comment]
I've created a unit test in a separate branch called [bug/double_colon](https://github.com/nkristek/ReactiveTimelane/tree/bug/double_colon) which reproduces this invalid behaviour.

**Comment by nkristek** [comment]
Maybe it's just the `outputTldr` property that is returning an invalid value.

**Comment by icanzilb** [comment]
Oh yeah I see, the test code is a bit lazy: https://github.com/icanzilb/TimelaneCore/blob/master/Tests/TimelaneCoreTestUtils/TestLog.swift#L27 - I'll fix it to just break at the first colon, thanks for spotting this :)

**Comment by icanzilb** [comment]
@nkristek https://github.com/icanzilb/TimelaneCore/releases/tag/1.0.11 should have fixed the issue for you
